comment:
  layout: "diff"
  behavior: default

coverage:
  status:
    project: false
    patch:
      default:
        # basic
        target: 85%
        if_not_found: success
        if_ci_failed: error
        if_no_uploads: error
  ignore:
    - "examples"  # ignore folders and all its contents
    - "tests"  # ignore folders and all its contents
    - "src/ansys(aedt/toolkits/template/ui/*.py"  # ignore folders and all its contents
    - "src/ansys(aedt/toolkits/template/ui/common/*.py"  # ignore folders and all its contents
    - "src/ansys(aedt/toolkits/template/run_toolkit.py"  # ignore folders and all its contents
